### ISSUE TITLE
[FEATURE] Add cluster.routing.allocation.awareness.force.zone.values to the provider as a cluster setting

### ISSUE THREAD

**Issue by vinylen** [opensearch-project/terraform-provider-opensearch#202]
### Is your feature request related to a problem?
As of the latest version of the provider, we can manage the cluster.routing.allocation.awareness attribute, but not the cluster.routing.allocation.awareness.force.zone.values option, which are often combined together.

### What solution would you like?
It would be great if the provider could add support for "cluster.routing.allocation.awareness.force.zone.values" so that we don't have to manually add this option to the cluster settings.

### What alternatives have you considered?
Manually adding the cluster.routing.allocation.awareness.force.zone.values after terraform has run it's course.
### Do you have any additional context?
Here are some links to the option in question:

[opensearch.org - Forced awareness](https://opensearch.org/docs/2.15/tuning-your-cluster/#forced-awareness)
[elastic.org - Forced awareness](https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-cluster.html#forced-awareness)

**Comment by prudhvigodithi** [comment]
[Triage]
Looks to me like we should include the setting in https://github.com/opensearch-project/terraform-provider-opensearch/blob/main/provider/resource_opensearch_cluster_settings.go here so that user can pass using [opensearch_cluster_settings](https://registry.terraform.io/providers/opensearch-project/opensearch/latest/docs/resources/cluster_settings), @vinylen thanks for bringing this up, is there a way you can contribute to this change ? :)
Thank you 
@getsaurabh02

**Comment by prudhvigodithi** [comment]
Hey @vinylen I have PR open https://github.com/opensearch-project/terraform-provider-opensearch/pull/211 to support `cluster.routing.allocation.awareness.force.zone.values` with the list of zone.
Thank you 
@getsaurabh02

**Comment by prudhvigodithi** [comment]
The terraform provider [2.3.1](https://registry.terraform.io/providers/opensearch-project/opensearch/2.3.1) is released supporting `cluster.routing.allocation.awareness.force.zone.values`, @vinylen please take a look.
Thanks
